#!@fish@/bin/fish

set SCANIMAGE_ARGS --page-height 876.695 --resolution 300 \
    --ald=yes --swcrop=yes \
    --format tiff --batch=out%d.tiff

function canonicalize_path -a path
    @coreutils@/bin/realpath -P $path
end

function capitalize -a str
    set fst (string upper (string sub -s 1 -l 1 $str))
    set rest (string lower (string sub -s 2 $str))
    echo $fst$rest
end

function run_tesseract -a path -a output -a lang
    set pdfbase (@coreutils@/bin/basename -s .pdf $output)
    set input (@coreutils@/bin/mktemp -p $path)
    @coreutils@/bin/ls -1 $path/* | @gnused@/bin/sed -e "\|$input|d" > $input
    if [ -z $lang ]
        @tesseract4@/bin/tesseract $input $pdfbase pdf
    else
        @tesseract4@/bin/tesseract $input $pdfbase -l $lang pdf
    end
end

function scan_documents -a path -a src -a mode
    pushd $path
    @sane-backends@/bin/scanimage $SCANIMAGE_ARGS --source $src --mode $mode
    popd
end

argparse --name=ocr-documents 'l/lang=' 'o/output=' 's/source=' 'm/mode=' -- $argv

if set -q _flag_s
    set src (capitalize $_flag_s)
    set src "ADF $src"
else
    set src 'ADF Front'
end

if set -q _flag_m
    set mode (capitalize $_flag_m)
else
    set mode 'Lineart'
end


set lang $_flag_l
set staging (@coreutils@/bin/mktemp -d)

set output (canonicalize_path $_flag_o)

function clean_up_staging --on-event EXIT -e INT -e QUIT -e TERM
    @coreutils@/bin/rm -rf $staging
end

scan_documents $staging $src $mode
run_tesseract $staging $output $lang
