# sgdisk -o -n 1:0:+95871MiB -n 2:0:+2GiB -n 3:0:0 -t 1:8300 -t 2:8200 -t 3:EF00 /dev/vda
# mkfs -t xfs -L NixOS /dev/vda1
# mkswap -L Swap /dev/vda2
# mkfs -t vfat -n ESP -F 32 /dev/vda3

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "virtio_pci" "xhci_pci" "usb_storage" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/vda1";
      fsType = "xfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/vda3";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/vda2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
