# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.zfs.forceImportRoot = false;

  services.udev.extraRules = ''
    ACTION=="add|change", KERNEL=="sd[a-z]*[0-9]*|mmcblk[0-9]*p[0-9]*|nvme[0-9]*n[0-9]*p[0-9]*", ENV{ID_FS_TYPE}=="zfs_member", ATTR{../queue/scheduler}="none"
  '';
  services.zfs.autoScrub.enable = true;
  services.zfs.autoScrub.pools = [
    "meteia"
    "ultima-thule"
  ];

  fileSystems."/" = {
    device = "ultima-thule/system/root";
    fsType = "zfs";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/4FAA-B3D4";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "ultima-thule/user/home";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "ultima-thule/local/nix";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "ultima-thule/system/var";
    fsType = "zfs";
  };

  fileSystems."/srv/samba" = {
    device = "meteia/samba";
    fsType = "zfs";
  };

  fileSystems."/srv/time-machine" = {
    device = "meteia/time-machine";
    fsType = "zfs";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
